//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disco
    {
        public int IdDisco { get; set; }
        public string Titulo { get; set; }
        public string Artista { get; set; }
        public string GeneroMusical { get; set; }
        public string Año { get; set; }
        public string Distribuidora { get; set; }
        public Nullable<int> Ventas { get; set; }
        public Nullable<int> Disponibilidad { get; set; }
    }
}
